package com.ether.data.dao;

import com.ether.data.entity.Block;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface BlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Thu Apr 25 11:03:14 CST 2024
     */
    int deleteByPrimaryKey(BigDecimal number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Thu Apr 25 11:03:14 CST 2024
     */
    int insert(Block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Thu Apr 25 11:03:14 CST 2024
     */
    int insertSelective(Block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Thu Apr 25 11:03:14 CST 2024
     */
    Block selectByPrimaryKey(BigDecimal number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Thu Apr 25 11:03:14 CST 2024
     */
    int updateByPrimaryKeySelective(Block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated Thu Apr 25 11:03:14 CST 2024
     */
    int updateByPrimaryKey(Block record);

    Long selectAllCount();

    List<Block> selectAll();

    Block selectByHashOrNumber(@Param("number") BigDecimal number, @Param("hash") String hash);

    List<Map> lastedTranscationCount();

    List<Block> selectBlockCacheInfo(@Param("maxElementNumber") Long maxElementNumber);

    List<Block> selectBlockCacheInfoByFixedFreq();
}