package com.ether.data.dao;

import com.ether.data.entity.ContractVerfity;
import com.ether.data.entity.ContractVerfityWithBLOBs;

public interface ContractVerfityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_verfity
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    int deleteByPrimaryKey(String contractaddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_verfity
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    int insert(ContractVerfityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_verfity
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    int insertSelective(ContractVerfityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_verfity
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    ContractVerfityWithBLOBs selectByPrimaryKey(String contractaddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_verfity
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    int updateByPrimaryKeySelective(ContractVerfityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_verfity
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(ContractVerfityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_verfity
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    int updateByPrimaryKey(ContractVerfity record);

    int insertSelectiveCompileInfo(ContractVerfity record);
    int updateSelectiveCompileInfo(ContractVerfity record);
}