package com.ether.data.dao;

import com.ether.data.entity.Contract;

import java.util.List;
import java.util.Map;

public interface ContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Fri Mar 22 19:28:42 CST 2024
     */
    int deleteByPrimaryKey(String contractaddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Fri Mar 22 19:28:42 CST 2024
     */
    int insert(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Fri Mar 22 19:28:42 CST 2024
     */
    int insertSelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Fri Mar 22 19:28:42 CST 2024
     */
    Contract selectByPrimaryKey(String contractaddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Fri Mar 22 19:28:42 CST 2024
     */
    int updateByPrimaryKeySelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Fri Mar 22 19:28:42 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Fri Mar 22 19:28:42 CST 2024
     */
    int updateByPrimaryKey(Contract record);

    Map selectByContractAddress(String contractAddress);

    List<Map> selectAll();

    List<Contract> selectAllToken();
}