package com.ether.data.dao;

import com.ether.data.entity.Erc20Balance;
import com.ether.data.entity.Erc20BalanceKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface Erc20BalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    int deleteByPrimaryKey(Erc20BalanceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    int insert(Erc20Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    int insertSelective(Erc20Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    Erc20Balance selectByPrimaryKey(Erc20BalanceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    int updateByPrimaryKeySelective(Erc20Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erc20_balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    int updateByPrimaryKey(Erc20Balance record);

    List<Map> selectContractBalance(@Param("contractAddress") String contractAddress);

    List<Map> selectTokenByAddress(@Param("address") String address);
}