package com.ether.data.dao;

import com.ether.data.entity.MethodHash;

public interface MethodHashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    int deleteByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    int insert(MethodHash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    int insertSelective(MethodHash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    MethodHash selectByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    int updateByPrimaryKeySelective(MethodHash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    int updateByPrimaryKey(MethodHash record);
}