package com.ether.data.dao;

import com.ether.data.entity.MntPrice;

public interface MntPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    int insert(MntPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    int insertSelective(MntPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    MntPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    int updateByPrimaryKeySelective(MntPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    int updateByPrimaryKey(MntPrice record);
}