package com.ether.data.dao;

import com.ether.data.entity.PlatformBalance;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface PlatformBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    int deleteByPrimaryKey(String address);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    int insert(PlatformBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    int insertSelective(PlatformBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    PlatformBalance selectByPrimaryKey(String address);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    int updateByPrimaryKeySelective(PlatformBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    int updateByPrimaryKey(PlatformBalance record);


    List<Map> selectAllBalance(@Param("address") String address);
}