package com.ether.data.dao;

import com.ether.data.entity.SwapPairs;

import java.util.List;

public interface SwapPairsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap_pairs
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    int deleteByPrimaryKey(String pairAddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap_pairs
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    int insert(SwapPairs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap_pairs
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    int insertSelective(SwapPairs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap_pairs
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    SwapPairs selectByPrimaryKey(String pairAddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap_pairs
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    int updateByPrimaryKeySelective(SwapPairs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap_pairs
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    int updateByPrimaryKey(SwapPairs record);

    List<SwapPairs> selectAll();
}