package com.ether.data.dao;

import com.ether.data.entity.Transaction;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    int deleteByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    int insert(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    int insertSelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    Transaction selectByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    int updateByPrimaryKeySelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    int updateByPrimaryKey(Transaction record);

    Long selectAllTransactionCount();

    List<Map> selectAllTransaction();

    Map selectTransactionByHash(String hash);

    List<Map> selectTransactionByBlockHash(String blockHash);

    List<Map> selectTransactionByAddress(String address);

    List<Map> selectTransactionCacheInfo(@Param("blockNumber") Long blockNumber);

    List<Map> selectPlatformInternalRransaction(@Param("userAddress") String userAddress);
}