package com.ether.data.dao;

import com.ether.data.entity.TransactionErc20;
import com.ether.data.entity.TransactionErc20Key;
import com.ether.data.entity.TransactionPlatform;

import java.util.List;
import java.util.Map;

public interface TransactionErc20Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_erc20
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    int deleteByPrimaryKey(TransactionErc20Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_erc20
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    int insert(TransactionErc20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_erc20
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    int insertSelective(TransactionErc20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_erc20
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    TransactionErc20 selectByPrimaryKey(TransactionErc20Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_erc20
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    int updateByPrimaryKeySelective(TransactionErc20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_erc20
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    int updateByPrimaryKey(TransactionErc20 record);

    List<Map> getContractTransactionByContractAddress(String contractaddress);

    List<Map> getContractTransactionByAddress(String address);

    List<Map> selectAllContractTransation();

    List<Map> selectByTransactionHash(String transactionhash);

    Long getContractTransactionCountByAddress(String contractaddress);


    /****/
    List<Map> selectInternalTransactionByHash(String transactionTash);

    List<Map> selectInternalTransactionByAddress(String address);

    List<Map> getContractTransaction(String contractaddress, String address);

    List<Map> getTransactionLog(String contractAddress,String numberSql,  String topicSql, Integer limitCount, String order);
}