package com.ether.data.dao;

import com.ether.data.entity.TransactionPlatform;
import com.ether.data.entity.TransactionPlatformKey;

import java.util.List;

public interface TransactionPlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_platform
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    int deleteByPrimaryKey(TransactionPlatformKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_platform
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    int insert(TransactionPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_platform
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    int insertSelective(TransactionPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_platform
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    TransactionPlatform selectByPrimaryKey(TransactionPlatformKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_platform
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    int updateByPrimaryKeySelective(TransactionPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_platform
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    int updateByPrimaryKey(TransactionPlatform record);

    List<TransactionPlatform> selectByHash(String transactionTash);
}