package com.ether.data.dao;

import com.ether.data.entity.TransactionReceipt;

import java.util.Map;

public interface TransactionReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    int deleteByPrimaryKey(String transactionhash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    int insert(TransactionReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    int insertSelective(TransactionReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    TransactionReceipt selectByPrimaryKey(String transactionhash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    int updateByPrimaryKeySelective(TransactionReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    int updateByPrimaryKey(TransactionReceipt record);

    Map lastedTransactionFee();
}