#server
server:
  port: 9003
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/javascript
      - application/x-javascript
      - application/javascript
      - text/css
      - text/plain
      - application/json
    min-response-size: 1024

spring:
  profiles:
    active: main
  mvc:
    async:
      request-timeout: 200000
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  aop:
    proxy-target-class: true
    auto: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

logging:
  level:
    com.data.manger.biz.dao.slave: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

