package com.ether.data.entity;

public class ContractVerfity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.contractAddress
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private String contractaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.contractName
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private String contractname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.compilerVersion
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private String compilerversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.optimization
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private Integer optimization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.compileType
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private Integer compiletype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.licenseType
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private String licensetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.other
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private String other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.verifyStatus
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private Integer verifystatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.contractAddress
     *
     * @return the value of contract_verfity.contractAddress
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public String getContractaddress() {
        return contractaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.contractAddress
     *
     * @param contractaddress the value for contract_verfity.contractAddress
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setContractaddress(String contractaddress) {
        this.contractaddress = contractaddress == null ? null : contractaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.contractName
     *
     * @return the value of contract_verfity.contractName
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public String getContractname() {
        return contractname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.contractName
     *
     * @param contractname the value for contract_verfity.contractName
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setContractname(String contractname) {
        this.contractname = contractname == null ? null : contractname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.compilerVersion
     *
     * @return the value of contract_verfity.compilerVersion
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public String getCompilerversion() {
        return compilerversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.compilerVersion
     *
     * @param compilerversion the value for contract_verfity.compilerVersion
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setCompilerversion(String compilerversion) {
        this.compilerversion = compilerversion == null ? null : compilerversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.optimization
     *
     * @return the value of contract_verfity.optimization
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public Integer getOptimization() {
        return optimization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.optimization
     *
     * @param optimization the value for contract_verfity.optimization
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setOptimization(Integer optimization) {
        this.optimization = optimization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.compileType
     *
     * @return the value of contract_verfity.compileType
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public Integer getCompiletype() {
        return compiletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.compileType
     *
     * @param compiletype the value for contract_verfity.compileType
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setCompiletype(Integer compiletype) {
        this.compiletype = compiletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.licenseType
     *
     * @return the value of contract_verfity.licenseType
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public String getLicensetype() {
        return licensetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.licenseType
     *
     * @param licensetype the value for contract_verfity.licenseType
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setLicensetype(String licensetype) {
        this.licensetype = licensetype == null ? null : licensetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.other
     *
     * @return the value of contract_verfity.other
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.other
     *
     * @param other the value for contract_verfity.other
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.verifyStatus
     *
     * @return the value of contract_verfity.verifyStatus
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public Integer getVerifystatus() {
        return verifystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.verifyStatus
     *
     * @param verifystatus the value for contract_verfity.verifyStatus
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setVerifystatus(Integer verifystatus) {
        this.verifystatus = verifystatus;
    }
}