package com.ether.data.entity;

public class ContractVerfityCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity_code.id
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity_code.contractAddress
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    private String contractaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity_code.fileName
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity_code.filePath
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    private String filepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity_code.id
     *
     * @return the value of contract_verfity_code.id
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity_code.id
     *
     * @param id the value for contract_verfity_code.id
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity_code.contractAddress
     *
     * @return the value of contract_verfity_code.contractAddress
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    public String getContractaddress() {
        return contractaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity_code.contractAddress
     *
     * @param contractaddress the value for contract_verfity_code.contractAddress
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    public void setContractaddress(String contractaddress) {
        this.contractaddress = contractaddress == null ? null : contractaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity_code.fileName
     *
     * @return the value of contract_verfity_code.fileName
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity_code.fileName
     *
     * @param filename the value for contract_verfity_code.fileName
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity_code.filePath
     *
     * @return the value of contract_verfity_code.filePath
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity_code.filePath
     *
     * @param filepath the value for contract_verfity_code.filePath
     *
     * @mbg.generated Fri Mar 29 10:28:44 CST 2024
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }
}