package com.ether.data.entity;

public class ContractVerfityWithBLOBs extends ContractVerfity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.abi
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private String abi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.bytecode
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private String bytecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_verfity.deployedBytecode
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    private String deployedbytecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.abi
     *
     * @return the value of contract_verfity.abi
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public String getAbi() {
        return abi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.abi
     *
     * @param abi the value for contract_verfity.abi
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setAbi(String abi) {
        this.abi = abi == null ? null : abi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.bytecode
     *
     * @return the value of contract_verfity.bytecode
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public String getBytecode() {
        return bytecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.bytecode
     *
     * @param bytecode the value for contract_verfity.bytecode
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setBytecode(String bytecode) {
        this.bytecode = bytecode == null ? null : bytecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_verfity.deployedBytecode
     *
     * @return the value of contract_verfity.deployedBytecode
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public String getDeployedbytecode() {
        return deployedbytecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_verfity.deployedBytecode
     *
     * @param deployedbytecode the value for contract_verfity.deployedBytecode
     *
     * @mbg.generated Fri Mar 29 18:17:12 CST 2024
     */
    public void setDeployedbytecode(String deployedbytecode) {
        this.deployedbytecode = deployedbytecode == null ? null : deployedbytecode.trim();
    }
}