package com.ether.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Erc20Balance extends Erc20BalanceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erc20_balance.balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erc20_balance.updateTime
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erc20_balance.balance
     *
     * @return the value of erc20_balance.balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erc20_balance.balance
     *
     * @param balance the value for erc20_balance.balance
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erc20_balance.updateTime
     *
     * @return the value of erc20_balance.updateTime
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erc20_balance.updateTime
     *
     * @param updatetime the value for erc20_balance.updateTime
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}