package com.ether.data.entity;

public class Erc20BalanceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erc20_balance.address
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erc20_balance.contractAddress
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    private String contractaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erc20_balance.address
     *
     * @return the value of erc20_balance.address
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erc20_balance.address
     *
     * @param address the value for erc20_balance.address
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erc20_balance.contractAddress
     *
     * @return the value of erc20_balance.contractAddress
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    public String getContractaddress() {
        return contractaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erc20_balance.contractAddress
     *
     * @param contractaddress the value for erc20_balance.contractAddress
     *
     * @mbg.generated Tue Apr 09 17:25:09 CST 2024
     */
    public void setContractaddress(String contractaddress) {
        this.contractaddress = contractaddress == null ? null : contractaddress.trim();
    }
}