package com.ether.data.entity;

public class MethodHash {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_hash.hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_hash.method
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_hash.type
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_hash.hash
     *
     * @return the value of method_hash.hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_hash.hash
     *
     * @param hash the value for method_hash.hash
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_hash.method
     *
     * @return the value of method_hash.method
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_hash.method
     *
     * @param method the value for method_hash.method
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_hash.type
     *
     * @return the value of method_hash.type
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_hash.type
     *
     * @param type the value for method_hash.type
     *
     * @mbg.generated Wed Apr 24 10:35:12 CST 2024
     */
    public void setType(Integer type) {
        this.type = type;
    }
}