package com.ether.data.entity;

import java.util.Date;

public class MntPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_price.id
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_price.price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_price.date
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_price.id
     *
     * @return the value of mnt_price.id
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_price.id
     *
     * @param id the value for mnt_price.id
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_price.price
     *
     * @return the value of mnt_price.price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_price.price
     *
     * @param price the value for mnt_price.price
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_price.date
     *
     * @return the value of mnt_price.date
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_price.date
     *
     * @param date the value for mnt_price.date
     *
     * @mbg.generated Tue Apr 30 18:03:35 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }
}