package com.ether.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PlatformBalance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_balance.address
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_balance.balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_balance.updateTime
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_balance.address
     *
     * @return the value of platform_balance.address
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_balance.address
     *
     * @param address the value for platform_balance.address
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_balance.balance
     *
     * @return the value of platform_balance.balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_balance.balance
     *
     * @param balance the value for platform_balance.balance
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_balance.updateTime
     *
     * @return the value of platform_balance.updateTime
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_balance.updateTime
     *
     * @param updatetime the value for platform_balance.updateTime
     *
     * @mbg.generated Tue Mar 26 14:00:51 CST 2024
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}