package com.ether.data.entity;

import java.math.BigDecimal;

public class SwapTxKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.pair_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String pairAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.block_number
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal blockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.transaction_hash
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String transactionHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.index
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.pair_address
     *
     * @return the value of swap_tx.pair_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getPairAddress() {
        return pairAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.pair_address
     *
     * @param pairAddress the value for swap_tx.pair_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setPairAddress(String pairAddress) {
        this.pairAddress = pairAddress == null ? null : pairAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.block_number
     *
     * @return the value of swap_tx.block_number
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getBlockNumber() {
        return blockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.block_number
     *
     * @param blockNumber the value for swap_tx.block_number
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setBlockNumber(BigDecimal blockNumber) {
        this.blockNumber = blockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.transaction_hash
     *
     * @return the value of swap_tx.transaction_hash
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getTransactionHash() {
        return transactionHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.transaction_hash
     *
     * @param transactionHash the value for swap_tx.transaction_hash
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setTransactionHash(String transactionHash) {
        this.transactionHash = transactionHash == null ? null : transactionHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.index
     *
     * @return the value of swap_tx.index
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.index
     *
     * @param index the value for swap_tx.index
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}