package com.ether.data.entity;

public class SwapPairs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.pair_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String pairAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.token0_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String token0Address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.token1_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String token1Address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.token0_name
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String token0Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.token1_name
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String token1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.token0_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String token0Symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.token1_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String token1Symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.token0_decimals
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private Integer token0Decimals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.token1_decimals
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private Integer token1Decimals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.block_number
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private Long blockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_pairs.transaction_hash
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String transactionHash;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.pair_address
     *
     * @return the value of swap_pairs.pair_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getPairAddress() {
        return pairAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.pair_address
     *
     * @param pairAddress the value for swap_pairs.pair_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setPairAddress(String pairAddress) {
        this.pairAddress = pairAddress == null ? null : pairAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.token0_address
     *
     * @return the value of swap_pairs.token0_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getToken0Address() {
        return token0Address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.token0_address
     *
     * @param token0Address the value for swap_pairs.token0_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken0Address(String token0Address) {
        this.token0Address = token0Address == null ? null : token0Address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.token1_address
     *
     * @return the value of swap_pairs.token1_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getToken1Address() {
        return token1Address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.token1_address
     *
     * @param token1Address the value for swap_pairs.token1_address
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken1Address(String token1Address) {
        this.token1Address = token1Address == null ? null : token1Address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.token0_name
     *
     * @return the value of swap_pairs.token0_name
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getToken0Name() {
        return token0Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.token0_name
     *
     * @param token0Name the value for swap_pairs.token0_name
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken0Name(String token0Name) {
        this.token0Name = token0Name == null ? null : token0Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.token1_name
     *
     * @return the value of swap_pairs.token1_name
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getToken1Name() {
        return token1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.token1_name
     *
     * @param token1Name the value for swap_pairs.token1_name
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken1Name(String token1Name) {
        this.token1Name = token1Name == null ? null : token1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.token0_symbol
     *
     * @return the value of swap_pairs.token0_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getToken0Symbol() {
        return token0Symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.token0_symbol
     *
     * @param token0Symbol the value for swap_pairs.token0_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken0Symbol(String token0Symbol) {
        this.token0Symbol = token0Symbol == null ? null : token0Symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.token1_symbol
     *
     * @return the value of swap_pairs.token1_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getToken1Symbol() {
        return token1Symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.token1_symbol
     *
     * @param token1Symbol the value for swap_pairs.token1_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken1Symbol(String token1Symbol) {
        this.token1Symbol = token1Symbol == null ? null : token1Symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.token0_decimals
     *
     * @return the value of swap_pairs.token0_decimals
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public Integer getToken0Decimals() {
        return token0Decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.token0_decimals
     *
     * @param token0Decimals the value for swap_pairs.token0_decimals
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken0Decimals(Integer token0Decimals) {
        this.token0Decimals = token0Decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.token1_decimals
     *
     * @return the value of swap_pairs.token1_decimals
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public Integer getToken1Decimals() {
        return token1Decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.token1_decimals
     *
     * @param token1Decimals the value for swap_pairs.token1_decimals
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken1Decimals(Integer token1Decimals) {
        this.token1Decimals = token1Decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.block_number
     *
     * @return the value of swap_pairs.block_number
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public Long getBlockNumber() {
        return blockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.block_number
     *
     * @param blockNumber the value for swap_pairs.block_number
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setBlockNumber(Long blockNumber) {
        this.blockNumber = blockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_pairs.transaction_hash
     *
     * @return the value of swap_pairs.transaction_hash
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getTransactionHash() {
        return transactionHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_pairs.transaction_hash
     *
     * @param transactionHash the value for swap_pairs.transaction_hash
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setTransactionHash(String transactionHash) {
        this.transactionHash = transactionHash == null ? null : transactionHash.trim();
    }
}