package com.ether.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SwapTx extends SwapTxKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.amount0_in
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal amount0In;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.amount1_out
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal amount1Out;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.amount1_in
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal amount1In;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.amount0_out
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal amount0Out;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.rate01
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal rate01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.rate10
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal rate10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.sender
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.receiver
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.token0_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String token0Symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.token1_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private String token1Symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.time
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.amount0_in
     *
     * @return the value of swap_tx.amount0_in
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getAmount0In() {
        return amount0In;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.amount0_in
     *
     * @param amount0In the value for swap_tx.amount0_in
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setAmount0In(BigDecimal amount0In) {
        this.amount0In = amount0In;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.amount1_out
     *
     * @return the value of swap_tx.amount1_out
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getAmount1Out() {
        return amount1Out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.amount1_out
     *
     * @param amount1Out the value for swap_tx.amount1_out
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setAmount1Out(BigDecimal amount1Out) {
        this.amount1Out = amount1Out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.amount1_in
     *
     * @return the value of swap_tx.amount1_in
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getAmount1In() {
        return amount1In;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.amount1_in
     *
     * @param amount1In the value for swap_tx.amount1_in
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setAmount1In(BigDecimal amount1In) {
        this.amount1In = amount1In;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.amount0_out
     *
     * @return the value of swap_tx.amount0_out
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getAmount0Out() {
        return amount0Out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.amount0_out
     *
     * @param amount0Out the value for swap_tx.amount0_out
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setAmount0Out(BigDecimal amount0Out) {
        this.amount0Out = amount0Out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.rate01
     *
     * @return the value of swap_tx.rate01
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getRate01() {
        return rate01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.rate01
     *
     * @param rate01 the value for swap_tx.rate01
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setRate01(BigDecimal rate01) {
        this.rate01 = rate01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.rate10
     *
     * @return the value of swap_tx.rate10
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getRate10() {
        return rate10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.rate10
     *
     * @param rate10 the value for swap_tx.rate10
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setRate10(BigDecimal rate10) {
        this.rate10 = rate10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.sender
     *
     * @return the value of swap_tx.sender
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.sender
     *
     * @param sender the value for swap_tx.sender
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.receiver
     *
     * @return the value of swap_tx.receiver
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.receiver
     *
     * @param receiver the value for swap_tx.receiver
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.token0_symbol
     *
     * @return the value of swap_tx.token0_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getToken0Symbol() {
        return token0Symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.token0_symbol
     *
     * @param token0Symbol the value for swap_tx.token0_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken0Symbol(String token0Symbol) {
        this.token0Symbol = token0Symbol == null ? null : token0Symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.token1_symbol
     *
     * @return the value of swap_tx.token1_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public String getToken1Symbol() {
        return token1Symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.token1_symbol
     *
     * @param token1Symbol the value for swap_tx.token1_symbol
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setToken1Symbol(String token1Symbol) {
        this.token1Symbol = token1Symbol == null ? null : token1Symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.time
     *
     * @return the value of swap_tx.time
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.time
     *
     * @param time the value for swap_tx.time
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setTime(Date time) {
        this.time = time;
    }
}