package com.ether.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SwapTxPrice extends SwapTxKey {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.rate01
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal rate01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.rate10
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private BigDecimal rate10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap_tx.time
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    private Date time;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.rate01
     *
     * @return the value of swap_tx.rate01
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getRate01() {
        return rate01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.rate01
     *
     * @param rate01 the value for swap_tx.rate01
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setRate01(BigDecimal rate01) {
        this.rate01 = rate01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.rate10
     *
     * @return the value of swap_tx.rate10
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public BigDecimal getRate10() {
        return rate10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.rate10
     *
     * @param rate10 the value for swap_tx.rate10
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setRate10(BigDecimal rate10) {
        this.rate10 = rate10;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap_tx.time
     *
     * @return the value of swap_tx.time
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap_tx.time
     *
     * @param time the value for swap_tx.time
     *
     * @mbg.generated Fri May 10 11:31:21 CST 2024
     */
    public void setTime(Date time) {
        this.time = time;
    }
}