package com.ether.data.entity;

import java.math.BigDecimal;

public class TransactionPlatform extends TransactionPlatformKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_platform.from
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    private String from;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_platform.to
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    private String to;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_platform.value
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    private BigDecimal value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_platform.utc
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    private Long utc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_platform.from
     *
     * @return the value of transaction_platform.from
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_platform.from
     *
     * @param from the value for transaction_platform.from
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_platform.to
     *
     * @return the value of transaction_platform.to
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_platform.to
     *
     * @param to the value for transaction_platform.to
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public void setTo(String to) {
        this.to = to == null ? null : to.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_platform.value
     *
     * @return the value of transaction_platform.value
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_platform.value
     *
     * @param value the value for transaction_platform.value
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_platform.utc
     *
     * @return the value of transaction_platform.utc
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public Long getUtc() {
        return utc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_platform.utc
     *
     * @param utc the value for transaction_platform.utc
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public void setUtc(Long utc) {
        this.utc = utc;
    }
}