package com.ether.data.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Transaction implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.hash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.type
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.blockHash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String blockhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.blockNumber
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private Long blocknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.transactionIndex
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private Byte transactionindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.confirmations
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private Integer confirmations;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.from
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String from;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.gasPrice
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private BigDecimal gasprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.maxPriorityFeePerGas
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private BigDecimal maxpriorityfeepergas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.maxFeePerGas
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private BigDecimal maxfeepergas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.gasLimit
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private BigDecimal gaslimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.to
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String to;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.value
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private BigDecimal value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.nonce
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private Integer nonce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.methodHash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String methodhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.r
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String r;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.s
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String s;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.v
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private Integer v;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.creates
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String creates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.chainId
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private Integer chainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.data
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.hash
     *
     * @return the value of transaction.hash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.hash
     *
     * @param hash the value for transaction.hash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.type
     *
     * @return the value of transaction.type
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.type
     *
     * @param type the value for transaction.type
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.blockHash
     *
     * @return the value of transaction.blockHash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getBlockhash() {
        return blockhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.blockHash
     *
     * @param blockhash the value for transaction.blockHash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setBlockhash(String blockhash) {
        this.blockhash = blockhash == null ? null : blockhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.blockNumber
     *
     * @return the value of transaction.blockNumber
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public Long getBlocknumber() {
        return blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.blockNumber
     *
     * @param blocknumber the value for transaction.blockNumber
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setBlocknumber(Long blocknumber) {
        this.blocknumber = blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.transactionIndex
     *
     * @return the value of transaction.transactionIndex
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public Byte getTransactionindex() {
        return transactionindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.transactionIndex
     *
     * @param transactionindex the value for transaction.transactionIndex
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setTransactionindex(Byte transactionindex) {
        this.transactionindex = transactionindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.confirmations
     *
     * @return the value of transaction.confirmations
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public Integer getConfirmations() {
        return confirmations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.confirmations
     *
     * @param confirmations the value for transaction.confirmations
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setConfirmations(Integer confirmations) {
        this.confirmations = confirmations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.from
     *
     * @return the value of transaction.from
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.from
     *
     * @param from the value for transaction.from
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.gasPrice
     *
     * @return the value of transaction.gasPrice
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public BigDecimal getGasprice() {
        return gasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.gasPrice
     *
     * @param gasprice the value for transaction.gasPrice
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setGasprice(BigDecimal gasprice) {
        this.gasprice = gasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.maxPriorityFeePerGas
     *
     * @return the value of transaction.maxPriorityFeePerGas
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public BigDecimal getMaxpriorityfeepergas() {
        return maxpriorityfeepergas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.maxPriorityFeePerGas
     *
     * @param maxpriorityfeepergas the value for transaction.maxPriorityFeePerGas
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setMaxpriorityfeepergas(BigDecimal maxpriorityfeepergas) {
        this.maxpriorityfeepergas = maxpriorityfeepergas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.maxFeePerGas
     *
     * @return the value of transaction.maxFeePerGas
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public BigDecimal getMaxfeepergas() {
        return maxfeepergas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.maxFeePerGas
     *
     * @param maxfeepergas the value for transaction.maxFeePerGas
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setMaxfeepergas(BigDecimal maxfeepergas) {
        this.maxfeepergas = maxfeepergas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.gasLimit
     *
     * @return the value of transaction.gasLimit
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public BigDecimal getGaslimit() {
        return gaslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.gasLimit
     *
     * @param gaslimit the value for transaction.gasLimit
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setGaslimit(BigDecimal gaslimit) {
        this.gaslimit = gaslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.to
     *
     * @return the value of transaction.to
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.to
     *
     * @param to the value for transaction.to
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setTo(String to) {
        this.to = to == null ? null : to.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.value
     *
     * @return the value of transaction.value
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.value
     *
     * @param value the value for transaction.value
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.nonce
     *
     * @return the value of transaction.nonce
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public Integer getNonce() {
        return nonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.nonce
     *
     * @param nonce the value for transaction.nonce
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setNonce(Integer nonce) {
        this.nonce = nonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.methodHash
     *
     * @return the value of transaction.methodHash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getMethodhash() {
        return methodhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.methodHash
     *
     * @param methodhash the value for transaction.methodHash
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setMethodhash(String methodhash) {
        this.methodhash = methodhash == null ? null : methodhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.r
     *
     * @return the value of transaction.r
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getR() {
        return r;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.r
     *
     * @param r the value for transaction.r
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setR(String r) {
        this.r = r == null ? null : r.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.s
     *
     * @return the value of transaction.s
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getS() {
        return s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.s
     *
     * @param s the value for transaction.s
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setS(String s) {
        this.s = s == null ? null : s.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.v
     *
     * @return the value of transaction.v
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public Integer getV() {
        return v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.v
     *
     * @param v the value for transaction.v
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setV(Integer v) {
        this.v = v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.creates
     *
     * @return the value of transaction.creates
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getCreates() {
        return creates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.creates
     *
     * @param creates the value for transaction.creates
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setCreates(String creates) {
        this.creates = creates == null ? null : creates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.chainId
     *
     * @return the value of transaction.chainId
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public Integer getChainid() {
        return chainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.chainId
     *
     * @param chainid the value for transaction.chainId
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setChainid(Integer chainid) {
        this.chainid = chainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.data
     *
     * @return the value of transaction.data
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.data
     *
     * @param data the value for transaction.data
     *
     * @mbg.generated Wed Apr 24 09:50:30 CST 2024
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}