package com.ether.data.entity;

public class TransactionErc20Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.transactionHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private String transactionhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.blockHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private String blockhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.contractAddress
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private String contractaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.index
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.transactionHash
     *
     * @return the value of transaction_erc20.transactionHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public String getTransactionhash() {
        return transactionhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.transactionHash
     *
     * @param transactionhash the value for transaction_erc20.transactionHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setTransactionhash(String transactionhash) {
        this.transactionhash = transactionhash == null ? null : transactionhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.blockHash
     *
     * @return the value of transaction_erc20.blockHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public String getBlockhash() {
        return blockhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.blockHash
     *
     * @param blockhash the value for transaction_erc20.blockHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setBlockhash(String blockhash) {
        this.blockhash = blockhash == null ? null : blockhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.contractAddress
     *
     * @return the value of transaction_erc20.contractAddress
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public String getContractaddress() {
        return contractaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.contractAddress
     *
     * @param contractaddress the value for transaction_erc20.contractAddress
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setContractaddress(String contractaddress) {
        this.contractaddress = contractaddress == null ? null : contractaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.index
     *
     * @return the value of transaction_erc20.index
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.index
     *
     * @param index the value for transaction_erc20.index
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}