package com.ether.data.entity;

public class TransactionErc20 extends TransactionErc20Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.methodHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private String methodhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.blockNumber
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private Long blocknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.from
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private String from;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.to
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private String to;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_erc20.value
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.methodHash
     *
     * @return the value of transaction_erc20.methodHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public String getMethodhash() {
        return methodhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.methodHash
     *
     * @param methodhash the value for transaction_erc20.methodHash
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setMethodhash(String methodhash) {
        this.methodhash = methodhash == null ? null : methodhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.blockNumber
     *
     * @return the value of transaction_erc20.blockNumber
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public Long getBlocknumber() {
        return blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.blockNumber
     *
     * @param blocknumber the value for transaction_erc20.blockNumber
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setBlocknumber(Long blocknumber) {
        this.blocknumber = blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.from
     *
     * @return the value of transaction_erc20.from
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.from
     *
     * @param from the value for transaction_erc20.from
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.to
     *
     * @return the value of transaction_erc20.to
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.to
     *
     * @param to the value for transaction_erc20.to
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setTo(String to) {
        this.to = to == null ? null : to.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_erc20.value
     *
     * @return the value of transaction_erc20.value
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_erc20.value
     *
     * @param value the value for transaction_erc20.value
     *
     * @mbg.generated Wed Apr 24 10:45:12 CST 2024
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}