package com.ether.data.entity;

import java.util.Date;

public class TransactionCountPerDay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_count_per_day.date
     *
     * @mbg.generated Sun Apr 28 15:23:28 CST 2024
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_count_per_day.count
     *
     * @mbg.generated Sun Apr 28 15:23:28 CST 2024
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_count_per_day.date
     *
     * @return the value of transaction_count_per_day.date
     *
     * @mbg.generated Sun Apr 28 15:23:28 CST 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_count_per_day.date
     *
     * @param date the value for transaction_count_per_day.date
     *
     * @mbg.generated Sun Apr 28 15:23:28 CST 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_count_per_day.count
     *
     * @return the value of transaction_count_per_day.count
     *
     * @mbg.generated Sun Apr 28 15:23:28 CST 2024
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_count_per_day.count
     *
     * @param count the value for transaction_count_per_day.count
     *
     * @mbg.generated Sun Apr 28 15:23:28 CST 2024
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}