package com.ether.data.entity;

public class TransactionPlatformKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_platform.transactionHash
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    private String transactionhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_platform.index
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_platform.transactionHash
     *
     * @return the value of transaction_platform.transactionHash
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public String getTransactionhash() {
        return transactionhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_platform.transactionHash
     *
     * @param transactionhash the value for transaction_platform.transactionHash
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public void setTransactionhash(String transactionhash) {
        this.transactionhash = transactionhash == null ? null : transactionhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_platform.index
     *
     * @return the value of transaction_platform.index
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_platform.index
     *
     * @param index the value for transaction_platform.index
     *
     * @mbg.generated Tue Apr 30 16:59:41 CST 2024
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}