package com.ether.data.entity;

import java.math.BigDecimal;

public class TransactionReceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.transactionHash
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private String transactionhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.from
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private String from;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.to
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private String to;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.contractAddress
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private String contractaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.transactionIndex
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private Byte transactionindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.gasUsed
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private BigDecimal gasused;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.logsBloom
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private String logsbloom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.blockHash
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private String blockhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.blockNumber
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private Long blocknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.confirmations
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private Integer confirmations;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.cumulativeGasUsed
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private BigDecimal cumulativegasused;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.effectiveGasPrice
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private BigDecimal effectivegasprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.status
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.type
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt.byzantium
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    private Boolean byzantium;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.transactionHash
     *
     * @return the value of transaction_receipt.transactionHash
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public String getTransactionhash() {
        return transactionhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.transactionHash
     *
     * @param transactionhash the value for transaction_receipt.transactionHash
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setTransactionhash(String transactionhash) {
        this.transactionhash = transactionhash == null ? null : transactionhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.from
     *
     * @return the value of transaction_receipt.from
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.from
     *
     * @param from the value for transaction_receipt.from
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.to
     *
     * @return the value of transaction_receipt.to
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.to
     *
     * @param to the value for transaction_receipt.to
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setTo(String to) {
        this.to = to == null ? null : to.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.contractAddress
     *
     * @return the value of transaction_receipt.contractAddress
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public String getContractaddress() {
        return contractaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.contractAddress
     *
     * @param contractaddress the value for transaction_receipt.contractAddress
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setContractaddress(String contractaddress) {
        this.contractaddress = contractaddress == null ? null : contractaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.transactionIndex
     *
     * @return the value of transaction_receipt.transactionIndex
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public Byte getTransactionindex() {
        return transactionindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.transactionIndex
     *
     * @param transactionindex the value for transaction_receipt.transactionIndex
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setTransactionindex(Byte transactionindex) {
        this.transactionindex = transactionindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.gasUsed
     *
     * @return the value of transaction_receipt.gasUsed
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public BigDecimal getGasused() {
        return gasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.gasUsed
     *
     * @param gasused the value for transaction_receipt.gasUsed
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setGasused(BigDecimal gasused) {
        this.gasused = gasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.logsBloom
     *
     * @return the value of transaction_receipt.logsBloom
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public String getLogsbloom() {
        return logsbloom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.logsBloom
     *
     * @param logsbloom the value for transaction_receipt.logsBloom
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setLogsbloom(String logsbloom) {
        this.logsbloom = logsbloom == null ? null : logsbloom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.blockHash
     *
     * @return the value of transaction_receipt.blockHash
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public String getBlockhash() {
        return blockhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.blockHash
     *
     * @param blockhash the value for transaction_receipt.blockHash
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setBlockhash(String blockhash) {
        this.blockhash = blockhash == null ? null : blockhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.blockNumber
     *
     * @return the value of transaction_receipt.blockNumber
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public Long getBlocknumber() {
        return blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.blockNumber
     *
     * @param blocknumber the value for transaction_receipt.blockNumber
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setBlocknumber(Long blocknumber) {
        this.blocknumber = blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.confirmations
     *
     * @return the value of transaction_receipt.confirmations
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public Integer getConfirmations() {
        return confirmations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.confirmations
     *
     * @param confirmations the value for transaction_receipt.confirmations
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setConfirmations(Integer confirmations) {
        this.confirmations = confirmations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.cumulativeGasUsed
     *
     * @return the value of transaction_receipt.cumulativeGasUsed
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public BigDecimal getCumulativegasused() {
        return cumulativegasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.cumulativeGasUsed
     *
     * @param cumulativegasused the value for transaction_receipt.cumulativeGasUsed
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setCumulativegasused(BigDecimal cumulativegasused) {
        this.cumulativegasused = cumulativegasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.effectiveGasPrice
     *
     * @return the value of transaction_receipt.effectiveGasPrice
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public BigDecimal getEffectivegasprice() {
        return effectivegasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.effectiveGasPrice
     *
     * @param effectivegasprice the value for transaction_receipt.effectiveGasPrice
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setEffectivegasprice(BigDecimal effectivegasprice) {
        this.effectivegasprice = effectivegasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.status
     *
     * @return the value of transaction_receipt.status
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.status
     *
     * @param status the value for transaction_receipt.status
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.type
     *
     * @return the value of transaction_receipt.type
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.type
     *
     * @param type the value for transaction_receipt.type
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt.byzantium
     *
     * @return the value of transaction_receipt.byzantium
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public Boolean getByzantium() {
        return byzantium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt.byzantium
     *
     * @param byzantium the value for transaction_receipt.byzantium
     *
     * @mbg.generated Thu Mar 21 09:48:59 CST 2024
     */
    public void setByzantium(Boolean byzantium) {
        this.byzantium = byzantium;
    }
}